# Generated by Django 3.1.7 on 2021-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0002_auto_20210224_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
